name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XAMPPRocky/get-github-release@v1
        with:
          matches: linux
          owner: getzola
          repo: zola
          token: "${{ secrets.GITHUB_TOKEN }}"
          install_path: /usr/bin/env
      - run: zola build
      - name: Deploy to GitHub Pages
        run: |
          curl -LsSf https://raw.githubusercontent.com/rust-lang/simpleinfra/master/setup-deploy-keys/src/deploy.rs | rustc - -o /tmp/deploy
          (cd public/ && /tmp/deploy)
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
        if: github.ref == 'refs/heads/master'
