name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XAMPPRocky/get-github-release@v1
        with:
          matches: linux
          owner: getzola
          repo: zola
          token: "${{ secrets.GITHUB_TOKEN }}"
      - run: /tmp/zola build
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ github.SECRET_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
